[project]
name = 'Carbon-Credit-Trading-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.carbon-credit-tokenization]
path = 'contracts/carbon-credit-tokenization.clar'
clarity_version = 2
epoch = 2.5

[contracts.trading]
path = 'contracts/trading.clar'
clarity_version = 2
epoch = 2.5

[contracts.verification]
path = 'contracts/verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
